// Generated by CoffeeScript 2.6.1
(function() {
  /*
  - web
    -  webpack / vite / rollup
    -  vue / react / angular
    -  coffeescript ?
    -  pug stylus ?
    -  jsex ?
    -  theme support ?
  */
  var Q, cfging, inquirer;

  Q = [
    {
      k: 'tool',
      q: 'Choose a tool for building your app.',
      opt: ['vite',
    'webpack',
    'rollup']
    },
    {
      k: 'lib',
      q: 'Choose a engine for boot your app.',
      opt: ['vue',
    'react',
    'angular']
    },
    {
      t: 'checkbox',
      k: 'more',
      q: 'Add addtion configs to initial your app.',
      opt: [
        {
          value: 'coffee',
          name: 'coffee: use coffeescript'
        },
        {
          value: 'pug/stylus',
          name: 'pug/stylus: use pug html engine and stylus css enginer.'
        },
        {
          value: 'theme',
          name: 'theme: add skin support for your app'
        },
        {
          value: 'jsex',
          name: 'jsex: extend js prototype.'
        }
      ]
    },
    {
      t: 'input',
      r: true,
      k: 'app',
      q: 'Enter your app name.'
    }
  ];

  inquirer = require('inquirer');

  module.exports = function() {
    console.log('cfging project steply.');
    return inquirer.prompt(Q.map(function({t, r, k, q, opt, multiple}) {
      return {
        type: t || 'list',
        name: k,
        message: q,
        choices: opt,
        validate: function(v, vs) {
          return !r || !!v;
        }
      };
    })).then(cfging);
  };

  cfging = function(cfg) {
    // console.log """Your config is #{JSON.stringify(cfg, null, 2)}"""
    return console.log('Not implemented!');
  };

}).call(this);
