// Generated by CoffeeScript 2.6.1
(function() {
  module.exports = {
    vue: 'git@github.com:joeyrenhuang/web-tpls.git/vue-vite-app',
    react: 'git@github.com:joeyrenhuang/web-tpls.git/react-vite-app',
    angular: 'git@github.com:joeyrenhuang/web-tpls.git/angular-cli-app',
    svelte: 'git@github.com:joeyrenhuang/web-tpls.git/svelte-vite-app',
    jsex: 'git@github.com:joeyrenhuang/jsex.git/src',
    css: 'git@github.com:joeyrenhuang/css.git/src'
  };

}).call(this);
