#!/usr/bin/env node
// Generated by CoffeeScript 2.6.1
(function() {
  //!/usr/bin/env coffee

  // enter point
  var cmds, init, program;

  ({program} = require('commander'));

  // cmd handler fn
  ({init} = require('./handlers'));

  // expose all useable command line interface here
  cmds = [
    {
      n: 'init',
      msg: 'complete initial by answer questions steply.',
      args: [
        {
          n: '[template]',
          msg: 'template you want use'
        },
        {
          n: '[project]',
          msg: 'project name'
        }
      ],
      fn: init,
      isDefault: true
    }
  ];

  // config each cmd
  cmds.forEach(function({n, msg, args, fn, isDefault}) {
    var cmd;
    cmd = program.command(n, {isDefault}).description(msg).action(fn);
    if (args) {
      return args.forEach(function({n, msg}) {
        return cmd.argument(n, msg);
      });
    }
  });

  // install commands
  program.parse();

}).call(this);
